[package]
name = "componentize-go"
version = "0.1.0"
edition = "2024"

[lib]
name = "componentize_go"
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
regex = "1.12.2"
url = "2.5.7"
wat = { version = "1.243.0"}
wit-bindgen-go = "0.50.0"
wit-component = "0.243.0"
wit-parser = "0.243.0"
